### ISSUE TITLE
POST vs. GET Schema

### ISSUE THREAD

**Issue by 0mars** [alysivji/falcon-apispec#14]
Is there a way to provide different schemas, 1 for POST and 1 for GET
for instance there maybe a case when you want to POST without ids
and when you GET, you get an object with an ID or some other internal fields like date_created

**Comment by alysivji** [comment]
Sounds like you might nee two different schemas? I'm not sure I quite follow, could you demonstrate with an example?

**Comment by 0mars** [comment]
```
POST /api/blogs
{
"title": "t1"
}
```
```
GET /api/blogs
[{
"id": 234
"title": "t1"
"published_at": "2pm"
}]
```

These can be varations of the schema, the actual one representing the resource is the GET response, while the POST creates the resource, so need to validate that request body in that format, without ids...etc

My question is how to represent that in apispec ?

**Comment by alysivji** [comment]
You'll need to define schemas using Marshmallow and then you can pass them into apispec. Check out [Marshmallow docs](https://marshmallow.readthedocs.io/en/stable/quickstart.html) for more information

Closing the issue as it is out of scope for this library.

**Comment by 0mars** [comment]
Where are the docs for this part, how to define a POST body schema ?

```
        """Add new a post
                ---
                    summary: Add new post
                    responses:
                        201:
                            description: post added
                            schema: PostSchema
                        415:
                            description: Error: Unsupported Media Type

        """
```

part of
```

class PostCollection:
    schema = PostSchema

    def __init__(self, add_new_post: AddNewPostUseCase):
        self.add_new_post = add_new_post

    def on_post(self, req, resp):
        """Add new a post
                ---
                    summary: Add new post
                    responses:
                        201:
                            description: post added
                            schema: PostSchema
                        415:
                            description: Error: Unsupported Media Type

        """
        PostCollection.schema = AddNewPostSchema
        request_json = req.context['json']
        command = AddNewPostCommand(*request_json)

        post = self.add_new_post.exec(command)

        resp.status = falcon.HTTP_201
        resp.body = json.dumps(PostSchema.from_domain_object(post))

```

**Comment by 0mars** [comment]
you can define a response schema, but how to configure a request schema ?

**Comment by 0mars** [comment]
tried this, doesn't work as specified in swagger spec
```
"""Add new a post
                ---
                    summary: Add new post
                    parameters:
                        - in: body
                          name: addNewPost
                          description: Add new post request
                          schema: AddNewPostSchema
                    responses:
                        201:
                            description: post added
                            schema: PostSchema
                        415:
                            description: Error: Unsupported Media Type

        """
```

**Comment by alysivji** [comment]
Your issue is out of scope for this library; not quite sure what is wrong with your spec's format.

I spent some time updating my [falcon-batteries-included example repo](https://github.com/alysivji/falcon-batteries-included) to work with the latest versions of marshamallow, apispec, and falcon-apispec. You can see examples of how I've written up my specifications.

**Comment by 0mars** [comment]
thanks, will check it out
