### ISSUE TITLE
Can this be used with py2swagger?

### ISSUE THREAD

**Issue by chevalier-m** [alysivji/falcon-apispec#6]
Hello,

I'm very unaware and my question might actually be quite stupid, but is this usable with py2swagger or do I need to implement the creation of the apispec in my python code?

Thanks in advance !

**Comment by alysivji** [comment]
This is a separate application than py2swagger. You will need to implement the creation of apispec in your code with this plugin enabled.

There is example code in the Quickstart. A more detailed example can be found in my [falcon batteries included repo](https://github.com/alysivji/falcon-batteries-included/tree/master/app) (`routes.py` and `apispec.py`)

**Comment by chevalier-m** [comment]
Oh thanks for your repo, this will help faster than reading the whole docs given the fact I just need basic apidoc.

Thanks !

**Comment by alysivji** [comment]
Lemme know if you need a hand. Happy to help out; need to sit down and make these instructions a bit clearer.

**Comment by chevalier-m** [comment]
Yeah that might be useful to specify that this repo doesn't have anything to deal with `py2swagger` -yet-, neither with the py2swagger falcon plug-in (which didn't fit my usecase).
