### ISSUE TITLE
APISpec.add_path renamed to .path

### ISSUE THREAD

**Issue by dillonco** [alysivji/falcon-apispec#9]
I am getting this error: 
`AttributeError: 'APISpec' object has no attribute 'add_path'`

And it turns out they renamed it, more info: https://github.com/marshmallow-code/apispec/blob/dev/CHANGELOG.rst

> Backwards-incompatible: apispec.APISpec.add_path and apispec.APISpec.add_tag are renamed to apispec.APISpec.path and apispec.APISpec.tag.

**Comment by alysivji** [comment]
Thanks for the detailed bug report! Really appreciate you digging into the change!

I can get to this next weekend, but would welcome a PR. I can cut a new version and get this out on PyPI fairly quickly.
